version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
    profiles:
      - dependencies
    networks:
      - recipe-strapi-network

volumes:
  db:
    driver: local

networks:
  recipe-strapi-network:
    driver: bridge

